name: CI

on: [push, pull_request]



jobs:

  build-mac:
    runs-on: macos-10.15
    env:
      PYTHON_VERSION: 3.6.8
      MACOSX_DEPLOYMENT_TARGET: 10.9

    steps:
    - uses: actions/checkout@v2

    - name: Get Python
      run: curl https://www.python.org/ftp/python/${PYTHON_VERSION}/python-${PYTHON_VERSION}-macosx${MACOSX_DEPLOYMENT_TARGET}.pkg -o "python.pkg"

    - name: Verify download
      run: shasum -a 256 -c <<< '4bcd53faffc98d193ef7cdccd5668de3829c702af4db45258819a84a2cab60d0 *python.pkg'

    - name: Install Python
      run: |
        sudo installer -pkg python.pkg -target /
    - name: Setup venv
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
    - name: Build
      run: |
        source venv/bin/activate
        fbs freeze
        hdiutil create -volname Vial-CN -srcfolder "target/Vial-CN.app" -ov -format UDZO vial-mac.dmg
    - uses: actions/upload-artifact@v1
      with:
        name: vial-mac
        path: vial-mac.dmg

  